language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

matrix:
  allow_failures:
    - python: 3.2
    - python: 3.3

script:
  nosetests

before_install:
# Environment setup
  - sudo apt-get update -qq
  - sudo apt-get install git ghc cabal-install xserver-xephyr x11-apps happy alex
  - cabal update
# Setup XvFB
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
# Installation environment variables
  - export VIRT_ROOT=/home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}
  - export PKG_CONFIG_PATH=${VIRT_ROOT}/lib/pkgconfig
  - export LD_LIBRARY_PATH=${VIRT_ROOT}/lib
  - export CONFIG_OPTS="--prefix=${VIRT_ROOT} --includedir=/usr/include  --libdir=/usr/lib --datarootdir=/usr/share"
  - export PY_MAJOR=${TRAVIS_PYTHON_VERSION:0:1}
# Ubuntu 12.04 needs updated xcb-proto (>=1.7.1) to install latest xpyb
# See https://github.com/travis-ci/travis-ci/issues/2046
  - wget http://xcb.freedesktop.org/dist/xcb-proto-1.10.tar.bz2
  - tar xjf xcb-proto-1.10.tar.bz2
  - pushd xcb-proto-1.10
  - ./configure ${CONFIG_OPTS}
  - make -j3
  - sudo make install
  - popd
# Install pygobject (gobject module)
  - if [[ ${PY_MAJOR} == "2" ]]; then
      export GOBJ_SRC="pygobject-2.28.6.tar.bz2";
      export GOBJ_OPTS="--disable-introspection";
    else
      export GOBJ_SRC="pygobject-3.2.2.tar.xz";
      sudo apt-get install python-dev;
    fi
  - GOBJ_DIR=${GOBJ_SRC%.tar.*}
  - GOBJ_VER=${GOBJ_DIR#*-}
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/${GOBJ_VER%.*}/${GOBJ_SRC}
  - tar xf ${GOBJ_SRC}
  - pushd ${GOBJ_DIR}
  - ./configure ${CONFIG_OPTS} ${GOBJ_OPTS} || cat config.log
  - make -j3
  - sudo make install
  - popd
# Install git xcb-types
  - git clone https://github.com/tych0/xcb-types.git
  - pushd xcb-types
  - cabal install
  - popd
# Installl git xcffib
  - git clone https://github.com/tych0/xcffib.git
  - pushd xcffib
  - pip install -r requirements.txt
  - cabal install
  - make xcffib
  - pip install .
  - popd
# Update cairo (currently needed to use libqtile/pangocffi.py, see tycho/qtile#5)
  - git clone git://anongit.freedesktop.org/cairo
  - pushd cairo
  - git reset --hard 39b7d5138eb83cc2d4f3ab6039894cc61c7fe4c7 # Use same git HEAD as current 14.04
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j3
  - sudo make install
  - popd
# Install cairocffi w/xcffib support
  - git clone -b xcffib https://github.com/tych0/cairocffi.git
  - pushd cairocffi
  - pip install .
  - popd
# Install xpyb (xcb module used for tests - This will break Python 3 tests)
  - wget http://xcb.freedesktop.org/dist/xpyb-1.3.1.tar.bz2
  - tar xjf xpyb-1.3.1.tar.bz2
  - pushd xpyb-1.3.1
  - ./configure ${CONFIG_OPTS}
  - make -j3
  - sudo make install
  - popd

notifications:
  - email: false
