language: python

# Install trollius for 2, 3.2, and pypy
# Install either trollius or tulip for 3.3
# Asyncio is in the standard library for 3.4+
matrix:
  include:
    - python: 2.6
      env: EVENTLOOP=trollius
    - python: 2.7
      env: EVENTLOOP=trollius
    - python: 3.2
      env: EVENTLOOP=trollius
    - python: 3.3
      env: EVENTLOOP=trollius
    - python: 3.3
      env: EVENTLOOP=tulip
    - python: 3.4
      env: EVENTLOOP=asyncio
    - python: pypy
      env: EVENTLOOP=trollius

script:
  - make ckpatch

before_install:
# Environment setup
  - sudo apt-get update -qq
  - sudo apt-get install -qqy xserver-xephyr x11-apps
# Setup XvFB
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
# Ubuntu 12.04 uses old xcb-proto (xcb-proto 1.7)
# See https://github.com/travis-ci/travis-ci/issues/2046
  - wget http://xcb.freedesktop.org/dist/xcb-proto-1.10.tar.bz2
  - tar xjf xcb-proto-1.10.tar.bz2
  - pushd xcb-proto-1.10
  - ./configure --prefix=/usr
  - make -j3
  - sudo make install
  - popd

install:
# Installl requirements
  - pip install -r requirements.txt
  - if [[ ${EVENTLOOP} == "trollius" ]]; then pip install trollius; fi
  - if [[ ${EVENTLOOP} == "tulip" ]]; then pip install asyncio; fi

after_success:
  - coveralls

notifications:
  - email: false
