sudo: false
language: python

matrix:
  include:
    # Nose test suite
    - python: 2.7
      env: TOXENV=py27-trollius
    - python: 3.2
      env: TOXENV=py32-trollius
    - python: 3.3
      env: TOXENV=py33-trollius
    - python: 3.3
      env: TOXENV=py33-tulip
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: pypy
      env: TOXENV=pypy-trollius
    - python: pypy3
      env: TOXENV=pypy3-trollius
    - python: nightly
      env: TOXENV=py36
    # Packaging
    - python: 3.5
      env: TOXENV=packaging
    # Building docs
    - python: 2.7
      env: TOXENV=docs
    - python: 3.5
      env: TOXENV=docs
    # PEP8 checks
    - python: 2.7
      env: TOXENV=pep8
    - python: 3.5
      env: TOXENV=pep8
  allow_failures:
    - python: nightly

addons:
  apt:
    packages:
    - x11-apps
    - xserver-xephyr
    - xvfb
    - graphviz # for docs

before_install:
  # Setup XvFB
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install tox

script:
  - tox

notifications:
  email: false
